// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNekfulejCx9YoIhEM_Y19ny5nFshqLnc',
    appId: '1:53267084175:web:009d045bffb4e3d93c11fa',
    messagingSenderId: '53267084175',
    projectId: 'sharemarket-943f2',
    authDomain: 'sharemarket-943f2.firebaseapp.com',
    storageBucket: 'sharemarket-943f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTsgcRidoS-F3A-UCShBiA6L8SIdgnbtM',
    appId: '1:53267084175:android:4b165bfa2f87ff233c11fa',
    messagingSenderId: '53267084175',
    projectId: 'sharemarket-943f2',
    storageBucket: 'sharemarket-943f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOA6uxFRxWS-JlmozJ1uuAznMAo-6YS3Y',
    appId: '1:53267084175:ios:868394d45202fff53c11fa',
    messagingSenderId: '53267084175',
    projectId: 'sharemarket-943f2',
    storageBucket: 'sharemarket-943f2.firebasestorage.app',
    iosBundleId: 'com.example.marketsutra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOA6uxFRxWS-JlmozJ1uuAznMAo-6YS3Y',
    appId: '1:53267084175:ios:868394d45202fff53c11fa',
    messagingSenderId: '53267084175',
    projectId: 'sharemarket-943f2',
    storageBucket: 'sharemarket-943f2.firebasestorage.app',
    iosBundleId: 'com.example.marketsutra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNekfulejCx9YoIhEM_Y19ny5nFshqLnc',
    appId: '1:53267084175:web:041c65eefe7883a43c11fa',
    messagingSenderId: '53267084175',
    projectId: 'sharemarket-943f2',
    authDomain: 'sharemarket-943f2.firebaseapp.com',
    storageBucket: 'sharemarket-943f2.firebasestorage.app',
  );
}
